### ISSUE TITLE
suggestion: tie to debug setting

### ISSUE THREAD

**Issue by bnomei** [floriankarsten/kirby-ref#1]
exposing code like this quiet a security risk. to avoid mistakes on plugin users site you could add a check to only print data if `c::set('debug', true);` is set.

**Comment by iskrisis** [comment]
VERY GOOD point, never thought about it. 

I will implement the check when i have the time.

**Comment by iskrisis** [comment]
Fixed in latest commit. Hopefully its a good solution and people wont be suprised if they dont have kirby in debug mode. 

Actually... it is the right solution. Thx @bnomei

**Comment by bnomei** [comment]
just update the installation section of the readme and tell them about the change. ;-)

edit: nevermid. you did. maybe in **bold**?

**Comment by iskrisis** [comment]
@bnomei right i moved it and made it bold :).

Thx
